name:                ptxplain
version:             0.1.0.0
github:              "stephenswat/ptxplain"
license:             MPL-2.0
author:              "Stephen Nicholas Swatman"
copyright:           "2022 CERN"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- megaparsec

library:
  source-dirs: src

executables:
  ptxplain-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wextra
    - -Wall
    dependencies:
    - ptxplain
    - optparse-applicative
